### ISSUE TITLE
Are you really using spark?

### ISSUE THREAD

**Issue by Sraw** [sciencepal/dockers#1]
Well, as far as I think, you are not using spark correctly? Or let's say completely?

There is no configuration in `hive-site.xml`, but there should be at least `hive.execution.engine=spark` one. As the default `mr` is deprecated.

**Comment by sciencepal** [comment]
Not using Spark execution engine for Hive, Hive is using MR. I tried installing Tez as an execution engine, but running into some standard errors which I could not fix because I've been busy with some stuff lately. Will look into this.
