### ISSUE TITLE
Unable to access Spark webui at port 4040

### ISSUE THREAD

**Issue by rajabhathor** [sciencepal/dockers#8]
Hi, Great work ! Thanks!
But Unable to access Spark webui at port 4040 - appreciate any assistance.
Regards

**Comment by sciencepal** [comment]
Hi Raj,

I have not explored if Spark UI is enabled in my cluster. Going by https://stackoverflow.com/a/50669721/5321992, we see that SparkUI is up only when any Spark application is running. I have not specifically tested any application with Spark on my system. However, I have enabled Spark History Server which is up and running at http://172.20.1.1:8080/ (master) and http://172.20.1.2:8081/ (workers)

**Comment by sciencepal** [comment]
![Screenshot from 2020-12-09 20-23-16](https://user-images.githubusercontent.com/10510046/101645908-e77c0900-3a5c-11eb-9373-a2978d25088f.png)

FYI .. just checked spark web UI by running a sample example. Seems to be coming up when an app is running. However, I don't see the completed job in spark history server. Not sure what is the issue there. Need to take a closer look.

**Comment by rajabhathor** [comment]
Thanks for responding !
Very much appreciate all your excellent work !
Cheers
Raj
